name: 📖 Documentation issue
description: Report something incorrect or missing in documentation and help to improve our documentation
title: 'docs: '
labels: ["A-documentation"]
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for documentation requests, including:

        - Elaborating on a particular topic;
        - Updating external links;
        - anything else that doesn't require touching the codebase itself.

        If you followed the documentation but things don't work, take some time to consider if it's the documentation or the code that's wrong. In the latter, prefer using the "bug" template.

        We seldom close documentation pull requests unmerged. If your documentation request is:

        - Relevant to a significant proportion of StoneDB users;
        - Not documented elsewhere (or, if it is documented, the mention is in very undiscoverable places).

  - type: checkboxes
    attributes:
      label: Have you read the Contributing Guidelines on issues?
      options:
        - label: I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7/CONTRIBUTING.md).
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please provide as much info as possible.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
        If you do check this box, please send a pull request within 5 days so we can still delegate this to someone else.
      options:
        - label: I'd be willing to address this documentation request myself.